version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rentflow-net

  backend:
    image: TheWizard2026/rentflow-backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    networks:
      - rentflow-net

  frontend:
    image: TheWizard2026/rentflow-frontend:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rentflow-net

volumes:
  pgdata:

networks:
  rentflow-net:

