services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: ghcr.io/jenteverbruggen-boop/rentflow2.0:latest
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

volumes:
  pgdata:

