version: '3.8'

x-buildkit:
  DOCKER_BUILDKIT: "0"

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rentflow-net

  backend:
    build: ./backend
    restart: always
    env_file: .env
    depends_on:
      - db
    networks:
      - rentflow-net

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rentflow-net

volumes:
  pgdata:

networks:
  rentflow-net:
